version: '2'
# [TODO]: Replace sandvik-nlp with sandvik-myproject in this file

services:
  frontend:
    image: frontend-angular
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-app"
    volumes:
      - ./frontend/src:/app/src # for watching files
    ports:
      - "4200:4200"
  backend:
    image: backend-flask
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-app"
    volumes:
        - ./backend:/app # for watching files
    ports:
      - "8081:8081" # if changed, please change port in `frontend/proxy.conf.dev.json`


# Use an external named volume so that we can share gcp auth across containers
# Before first use, this volume must be manually created with
#   docker volume create --name=gcp
volumes:
  gcp:
    external: true


